### ISSUE TITLE
Trim SMCP yaml to supported fields

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#422]
The default ServiceMeshControlPlane CR contains fields that while in the schema, do not appear to be supported, and may cause issues if they are toggled.

Limit the fields in the default SMCP CR to those that are documented & supported.

**Comment by jgawor** [comment]
@dacleyra I thought deploying/managing SMCP is no longer needed with serverless operator 1.2+.

**Comment by dacleyra** [comment]
@jgawor you are thinking ServerMeshMemberRole (SMMR).

**Comment by dacleyra** [comment]
@jgawor actually, you are right. Serverless generates & owns an SMCP that is satisfactory.

SMCP will no longer be applied as part of #420

**Comment by marikaj123** [comment]
@jgawor and Dan, please pin the issue if it is a high priority or regression. Thank you.

**Comment by kaczyns** [comment]
@dacleyra it seems like this was fixed in #420.  If you agree, please close this issue.

**Comment by dacleyra** [comment]
merged, closing

**Comment by chayan88** [comment]
@dacleyra I have tested the installation again and looks like it is not yet fixed. Please find below the errors.

`Normal Scheduled 28m default-scheduler Successfully assigned istio-system/istio-sidecar-injector-65cd4c8c6f-qsrks to ip-10-0-145-205.ap-south-1.compute.internal
Warning FailedMount 6m (x10 over 26m) kubelet, ip-10-0-145-205.ap-south-1.compute.internal Unable to mount volumes for pod "istio-sidecar-injector-65cd4c8c6f-qsrks_istio-system(c7a37648-3ead-11ea-a250-0a69d1e53efc)": timeout expired waiting for volumes to attach or mount for pod "istio-system"/"istio-sidecar-injector-65cd4c8c6f-qsrks". list of unmounted volumes=[inject-config]. list of unattached volumes=[config-volume webhook certs inject-config istio-sidecar-injector-service-account-token-2jqpd]
Warning FailedMount 2m (x21 over 28m) kubelet, ip-10-0-145-205.ap-south-1.compute.internal MountVolume.SetUp failed for volume "inject-config" : configmap "istio-sidecar-injector" not found``
